1 html
ShCiv/DZ pull request #1
Opened 2024-02-28 08:11 UTC by ShCiv

2024-02-28 08:30 UTC, GitEsense requested changes
В целом - всё отлично, но некоторые блоки надо переделать, рекомендую ознакомиться с поведением заголовков и пройтись по блочным тегам, а так же "семантику", старайтесь не использовать заголовки вместо "текстового блока"

2024-02-28 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +    <title>Blog</title>
можно почитать дополнительно (об этом речи не шло в уроках) про указание мета-тегов, например:
```
<meta name="description" content="PurpleSchool HTML+CSS course">
<meta name="author" content="myname" />
```
Это не принципиально, но будет полезно)

2024-02-28 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +      </nav>
Семантически верно было бы использовать h1, по иерархии всегда идёт h1, за ним H2
К тому же nav блок хорошо бы оформить через список и сделать ссылками (т.к. это навигация и будет переводить на нужную страницу)

"Мой блог" же Вы верно вынесли за навигацию - это логотип, но так же ссылка
```html
<a>
<nav>
   <ul>
...
```

2024-02-28 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +      </div>
В данном примере "FRONTEND" можно было бы обернуть в span элемент, т.к. у Вас уже есть блочная обёртка, которая содержит текст + time, если же Вы оставите как есть, то тэг заголовка имеет блочное поведение и придётся принудительно выстраивать в одну линию в перспективе, либо вместо обёртки (div> воспользоваться заголовком или параграфом, а уже во вложенных элементах воспользоваться тегом time для выделения времени
```html
<h1>FRONTEND &bull; <time datetime="2001-05-12">12 мая 2024</time></h1>
```
или
```html
<p>FRONTEND &bull; <time datetime="2001-05-12">12 мая 2024</time></p>
```

2024-02-28 08:30 UTC, GitEsense commented on 1-Blog/index.html
> +        <h4>Разработчик</h4>
Тут так же лучше воспользоваться не заголовками, а блочным текстовым тегом "параграф" - p

2024-02-28 08:30 UTC, GitEsense commented on 2-Form/form.html
> +      </div>
Эту часть лучше будет вложить в форму, т.к. это является не заголовком страницы, а заголовком формы и в последующем лучше использовать их "одним блоком"

2024-02-28 08:30 UTC, GitEsense commented on 2-Form/form.html
> +          <label for="name"></label>
label не является обязательным элементом для инпутов и их можно убрать, если мы не оформляем через лейбл что-нибудь дополнительно или не сообщаем о чём-то, в прочем если он пустой - он никак не помешает, а вот в стилистике может и помочь, так что на Ваше усмотрение)

2024-02-28 08:30 UTC, GitEsense commented on 2-Form/form.html
> +        <input type="checkbox" name="condition" id="condition" />
Это так же является "footer"ом формы, а не отдельной частью страницы
Вы можете смело перенести header и footer в саму форму, разделив контент формы по семантике
```html
<form>
   <header>
   <main>
   <footer>
</form>

можно же и без семантических тегов, т.к. по форме будет понятно, что это форма и дальше идут поля ввода со своими метками

2024-02-28 12:35 UTC, ShCiv commented on 1-Blog/index.html
> +    <title>Blog</title>
Изучу со временем, спасибо.

2024-02-28 13:07 UTC, ShCiv commented
Исправила, как мне кажется все замечания.

2024-02-29 05:43 UTC, ShCiv commented
Исправила замечания, загрузила файлы, не могу понять просматривались изменения или ещё нет

2024-03-01 10:10 UTC, GitEsense reviewed
Всё отлично, исправления привели всё в порядок, но некоторые комментарии возьмите на исправление и обратите внимание на блоки и семантику, так же в рамках "упражнения" предлагаю Вам попробовать ещё и определить article / setcion (это на Ваше усмотрение в рамках упражнения - не обязательно)

Внесёте корректировки и сдавайте на платформе повторно

2024-03-01 10:10 UTC, GitEsense commented on 1-Blog/index.html
> +      <h2><a href="">Мой блог</a></h2>
Вот тут уже идёт нарушение семантики и иерархии заголовков, заголовки начинаются с h1 и т.д.
Я бы оформил это следующим образом
```html
   <a href="#"><img src="" alt="Иконка блога" />Мой блог</a>
```
Так мы говорим, что это ссылка, в ней есть изображение иконки и текст самой ссылки, при клике будет единое поведение
так же текст "Мой блог" - можно обернуть в span, но необходимости в данном случае нету, т.к. мы не вешаем "отдельные" стили \ поведение

2024-03-01 10:10 UTC, GitEsense commented on 1-Blog/index.html
>        </div>
Вот тут можно использовать просто
```html
<p>
   FRONTEND &bull; <time datetime="2001-05-12">12 мая 2024</time>
</p>
```
Говоря о том, что это текстовый блок "параграф", в нём есть текст "FRONTEND" символ и "время"
а обёртка div тут будет лишней (пустой), только если не планируем иного
или обернуть контент, где сказать
```html
<div>
   <span>FRONTEND</span> &bull; <time datetime="2001-05-12">12 мая 2024</time>
</div>
```
Говоря, что тут есть блок контента, в котором есть текст + символ + время

p.s. на 67 строке (footer) - h4 надобно бы заменить на параграф, так будет вернее (или обернуть просто в span), но параграф имеет блочное поведение и с ним работать будет проще

2024-03-01 10:10 UTC, GitEsense commented on 2-Form/form.html
> +        </div>
```html
<div>
   <p>Уже есть аккаунт?</p>
   <a href="https://example.com" target="_blank">Войти</a>
</div>
```
можно упростить до 
```html
<p>Уже есть аккаунт? <a href="https://example.com" target="_blank">Войти</a></p>
```
поведение будет абсолютно одинаковое в данном случае

2024-03-01 10:10 UTC, GitEsense commented on 2-Form/form.html
>            <label for="name"></label>
А вот тут пропущен инпут "Моя компания"

2024-03-01 10:10 UTC, GitEsense commented on 2-Form/form.html
>          <input type="checkbox" name="condition" id="condition" />
чтобы не позиционировать реверсом потом, лучше инпут поставить перед label

2024-03-01 10:57 UTC, GitEsense approved these changes
Всё отлично, но по section \ article всё-таки "освежите" знания, в форме они ни к чему в данном исполнении - в первую очередь они рассмтариваются для "семантического разделения контента, например часть кроме заголовка (статью) можно было бы обернуть в article и разделить на 2 секции внутри (первая про автора), вторая с изображением "контент" - итого выйдет
```html
<header>
<main>
   <article>
      <section>
         <h1>
         <div>
            <img>
            <div>
               <p>
               <p>
      <section>
         <img>
         <p>
         <p>
      <p>
<footer>

2024-03-01 12:24 UTC, ShCiv commented
> Всё отлично, но по section \ article всё-таки "освежите" знания, в форме они ни к чему в данном исполнении - в первую очередь они рассмтариваются для "семантического разделения контента, например часть кроме заголовка (статью) можно было бы обернуть в article и разделить на 2 секции внутри (первая про автора), вторая с изображением "контент" - итого выйдет
> 
> ```
> <header>
> <main>
>    <article>
>       <section>
>          <h1>
>          <div>
>             <img>
>             <div>
>                <p>
>                <p>
>       <section>
>          <img>
>          <p>
>          <p>
>       <p>
> <footer>
> ```

Кажется теперь ясно. Спасибо.

2024-03-01 12:25 UTC, merged